### ISSUE TITLE
Depletion/enrichemnt

### ISSUE THREAD

**Issue by lisavetasol** [bigbio/proteomics-metadata-standard#167]
It seems you have already started the discussion about enrichment column in [#20 ](https://github.com/bigbio/proteomics-metadata-standard/issues/20), but I cannot see this in the code, so : 
It would be nice to have some columns to specify the enrichment and depletion methods used. Since it could influence the search parameters and interpretation of the results.
For enrichment, it seems fairly easy, since there are a few commonly used strategies (e.g. phospho or Glyco, or even more specifically TiO2 enrichment). 
Depletion may be more tricky, so perhaps a yes/no option is a good choice.

**Comment by ypriverol** [comment]
> It seems you have already started the discussion about enrichment column in [#20 ](https://github.com/bigbio/proteomics-metadata-standard/issues/20), but I cannot see this in the code, so :
> It would be nice to have some columns to specify the enrichment and depletion methods used. Since it could influence the search parameters and interpretation of the results.

I think is fine. Do you think we should add that at the `sample` or `assay datafile` level? I vote to add this add the `sample`. 

> For enrichment, it seems fairly easy, since there are a few commonly used strategies (e.g. phospho or Glyco, or even more specifically TiO2 enrichment).

- The name of the column will be `characteristics[enrichment process]`

The current values in OLS for that property are https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009090&viewMode=All&siblings=false

I like to add the following cv terms, that are more align with the existing EFO style: 

- enrichment of phosphorylated Protein 
- enrichment of glycosylated Protein      

This will be align with other existing omics fields like: 

- enrichment of methylated DNA https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004185&viewMode=All&siblings=false

> Depletion may be more tricky, so perhaps a yes/no option is a good choice.

- `characteristics[depletion]` this will correspond to CVTerm https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000020&viewMode=All&siblings=false

I need to double check if the best way to annotate the boolean value is YES/NO or something else. @anjaf can you help me to decide what is the best way to annotate Boolean values?

**Comment by anjaf** [comment]
Hi, we generally tend to avoid using boolean values such as 'yes/no', '0/1' etc in our annotations. It's good to always be explicit: e.g. use "depletion/no depletion". (The rule of thumb here is "would the table still make sense if I take away the header?")
Although without knowing the subject area, I'm asking myself "what was depleted?". It might be too obvious for you add that explicitly but maybe not (or is that specified somewhere else in the parameters?).

**Comment by ypriverol** [comment]
I think this `sample process step`. 

Definion: 

`Abundant Protein Depletion for Mass Spectrometry. Depletion is used to reduce the complexity of biological samples such as serum, plasma, or biofluids, which contain high concentrations of albumin and immunoglobulins.`

**Comment by ypriverol** [comment]
@lisavetasol nice example about phosphoproteomics enrichment https://github.com/bigbio/proteomics-metadata-standard/pull/205

**Comment by ypriverol** [comment]
@lisavetasol we probably need to list all the methods for phospho-enrichment in details like:

- IMAC 
- TiO2 
-? 
Any other methods we would like to add.? @mvaudel @lisavetasol

**Comment by javizca** [comment]
Going a bit towards the top of this thread, there will be the need to create a generic term for "Enrichment for a given PTM," or probably a better solution will be to create generic terms for enrichment for particular PTMs (in addition to phosphorylation and glycosylation). Some additional examples are methylation, Ubiquitination or SUMOylation, among others. 

There are also other chemical enrichment methods e.g. for N-terminal peptides, that not really easy to "map" to enrichment for PTMs.

In terms of depletion, I think a generic term is probably enough for interpretation purposes (whether depletion has taken place or not, it could be a boolean), since as far as I can see, the main affected samples will be plasma and serum. There are different depletion methods for plasma (mostly mapped to commercial products) targeting for different sub-populations of proteins but the important thing is to know whether a sample has been depleted or not.

In terms of different methods of enrichment for a particular PTM, like the example for phosphor-enrichment above, I think this is of course good to have but less prioritary. It is true that some particular enrichment methods correspond to different types of phosphopeptides, but it is less important (analogous case to depletion).

**Comment by ypriverol** [comment]
> Going a bit towards the top of this thread, there will be the need to create a generic term for "Enrichment for a given PTM," or probably a better solution will be to create generic terms for enrichment for particular PTMs (in addition to phosphorylation and glycosylation). Some additional examples are methylation, Ubiquitination or SUMOylation, among others.

The current proposal contains a column name called characteristics[enrichment process]. Inside that terms the possible values are now: 

- enrichment of phosphorylated Protein
- enrichment of glycosylated Protein

If we want to create more terms, we can do it, we just need to ask to EFO. 
> 
> There are also other chemical enrichment methods e.g. for N-terminal peptides, that not really easy to "map" to enrichment for PTMs.
> 
In case we want to compare Modified-proteins expression vs non-modified for the samples that are not enriched we will need to think on a better way to do it. Agree. 

> In terms of depletion, I think a generic term is probably enough for interpretation purposes (whether depletion has taken place or not, it could be a boolean), since as far as I can see, the main affected samples will be plasma and serum. There are different depletion methods for plasma (mostly mapped to commercial products) targeting for different sub-populations of proteins but the important thing is to know whether a sample has been depleted or not.

@anjaf explain to us that instead of using a boolean we should use `no depletion` or `depletion`. this is also the style for other boolean fields now. 
> 
> In terms of different methods of enrichment for a particular PTM, like the example for phosphor-enrichment above, I think this is of course good to have but less prioritary. It is true that some particular enrichment methods correspond to different types of phosphopeptides, but it is less important (analogous case to depletion).

This has been requested by collaborators of the project. If the information is available, then we should have a way to encode it. I was looking into PSI-MS and those terms are not there, I'm trying to collect all the methods to update PRIDE ontology.

**Comment by lisavetasol** [comment]
> we probably need to list all the methods for phospho-enrichment in details like:
> 
> * IMAC
> * TiO2
>   -?
>   Any other methods we would like to add.?

Not really a big expert in enrichments, but at least there are a few types of IMAC - iron, titanium, nickel IMAC. Also SIMAC is a subclass of IMAC methods. There are lots of different antibodies for phospho enrichment as well. Check out Figure 2 in [this article ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3418503/).

**Comment by lisavetasol** [comment]
@ypriverol @anjaf One more question about depletion. 
There is a sample which is a bound fraction (not a depleted one as usual), so is it okay to specify in `characteristics[depletion]` - **depletion bound fraction** instead of just **depletion** as it is for a normal depleted fraction?  Would be also nice to add such term under [depletion ontology term](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000020&viewMode=All&siblings=false).

**Comment by ypriverol** [comment]
@lisavetasol you can do a PR in the PRIDE ontology and I will review it. Please feel free. Also, it will make things faster in terms of progression.

**Comment by levitsky** [comment]
By the way, it is `characteristics[depletion]`, right? That's what I see in annotations, but the README has `comment[depletion]`.

**Comment by ypriverol** [comment]
Can we close this issue? @levitsky @lisavetasol

**Comment by lisavetasol** [comment]
@ypriverol  We could, although there is a new issue #298 which closely related to this one. So maybe it's worth to discuss some enrichment methods?
