### ISSUE TITLE
search-metadata: universal and engine specific parameters

### ISSUE THREAD

**Issue by StSchulze** [bigbio/proteomics-metadata-standard#2]
The current search-metadata json contains an AnalysisSoftwareList (ASL) to list the employed engines and a SpectrumIdentificationProtocolList (SIPL) to list the used parameters.

I wanted to discuss here, how this deals with multiple engines, especially in regard to engines having common and unique parameters?
1. If the position in ASL corresponds to the position in SIPL, then all common parameters would occur multiple times in the different list entries.
2. If the position is not the same for both lists, but SIPL has just one list with all parameters, it is not clear which parameter belongs to which engine (for unique parameters).

It might also be worth it to first discuss if in general all parameters should be included or only the "important" or "common" ones, which then implies that someone would need to define which ones that would be.

I would be in favor of including all parameters and rather following 2. than 1.

**Comment by ypriverol** [comment]
The current approach responds to mzIdentML design. We are free to change it. We can have three approaches as you said: 

1- We repeat the  common search parameters for each search engine (e.g. FixMoficiations)

2- Have the parameters in one big list and all the search engines in another and as you said, would be difficult to associate search parameters - search engines. 

I strongly believe we need to have a way to represent first the common search engine parameters, like fixed/variable PTMs, precursor / fragment tolerances, and thresholds.  In mzIdentML, we have a collection for each set of parameters for example and each search engine reference the collection that is using in the common. Example: 

Software 1: 
   Using Parameters Collection 1. 
   Own parameters. 

This nested / reference approach allows reusing collections of parameters by different search engines.  The bad thing with that approach is that you need to start reading the file and make the links with your tool. 

**About the Unique Parameters for each search engine.** This is the more complex part to standardized for multiple reasons: 

1- Is the most dynamic part of the definition, this can be changing all the time from software version to software versions etc. 

2 - The number of own parameters can grow really fast. Relying for example in CVP Params here is not practical because it can delay the implementation itself. Also the number of "custom" parameters can be huge and difficult to move into ontologies. We can end up writing more CvTerms definition than actual implementations. 

For the unique/specific parameters I will suggest to review https://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter
