### ISSUE TITLE
How to annotate "anomalous" samples?

### ISSUE THREAD

**Issue by levitsky** [bigbio/proteomics-metadata-standard#211]
We are annotating samples with terms from [organism part](http://www.ebi.ac.uk/efo/EFO_0000635) subtree. I am not sure what to do when samples are things like cyst fluid. Cysts are not normally part of the human anatomy and thus I can't find a relevant ontology term. Specific example is pancreatic cyst fluid. What would be the right way to annotate the sample?

Additionally, there is one "normal" sample that I can't find a term for: aqueous humor. Should I just use [`eye`](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000970&viewMode=All&siblings=false)?

**Comment by anjaf** [comment]
Generally, for fluids there is a term called "organism substance" that fits better than "organism part". So you can use this instead of organism part. 
For cysts and tumours and other non-normal body parts, many can be found in the ontologies nevertheless. However, if you can't find a suitable term, a possible workaround is specifying the main organ as organism part (here "eye"?) and then use "sampling site: cyst fluid" to specify the details of the actual part that was taken.
I've found the term for "aqueous humor" in UBERON: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001796&viewMode=All&siblings=false

**Comment by ypriverol** [comment]
@levitsky can we close this issue.

**Comment by levitsky** [comment]
I'm not sure we're not going to see similar issues while submitting our annotations. I tried to make it relatively general, while the suggestion from @anjaf is more specific. For this reason I reserved the thought of maybe updating it with more questions as we go.
Feel free to close it for now if you prefer to.
