### ISSUE TITLE
Allow sdrf annotations with gz files 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#257]
@levitsky we can start having sdrf.txt that contains sdrf.txt.gz because they are too big for GitHub in decompress mode. I think we should allow in the validator to validate sdrf.txt.gz

**Comment by levitsky** [comment]
What do you mean exactly? Github file size limit is [100 MB per file](https://help.github.com/en/github/managing-large-files/conditions-for-large-files), right now the largest annotation file is 1.5 MB and 2.2k lines. So, we can have up to ~150k rows per table without compression.
Do you think it is not enough?

**Comment by ypriverol** [comment]
We have an internal discussion that in single-cell experiments, you can have a line per cell (right now in transcriptomics), we have seen already files of 120 MB. This is a feature for the future.

**Comment by levitsky** [comment]
OK, I checked it and `pandas` actually infers compression automatically. The validator already works fine with gzipped files. The only change needed is in the validation script, because now it only matches `*.tsv` files. However, if I relax the glob, it also starts matching `.wrong` files and validation fails. Seeing as there are only a couple of those left to fix, I don't want to think too much about inventing a workaround.

**Comment by levitsky** [comment]
Looks like nothing else needs to be done here?
